//! Routing protocol management for QuickFW.
//!
//! Provides OSPF and BGP configuration, FRR config generation,
//! and vtysh integration for runtime queries.

pub mod ospf;
pub mod bgp;
pub mod rip;

use serde::{Deserialize, Serialize};

/// Static route entry.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct StaticRoute {
    pub cidr: String,
    pub gateway: String,
    #[serde(default = "default_metric")]
    pub metric: u64,
}

fn default_metric() -> u64 { 100 }

/// Static routes configuration.
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct StaticRoutesConfig {
    #[serde(default)]
    pub routes: Vec<StaticRoute>,
}

const ROUTES_CONFIG_PATH: &str = "/etc/quickfw/routes.yaml";

/// Load static routes from disk.
pub fn load_static_routes() -> StaticRoutesConfig {
    match std::fs::read_to_string(ROUTES_CONFIG_PATH) {
        Ok(contents) => match serde_yaml::from_str(&contents) {
            Ok(config) => config,
            Err(e) => {
                tracing::error!("Failed to parse routes config: {}", e);
                StaticRoutesConfig::default()
            }
        },
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => {
            StaticRoutesConfig::default()
        }
        Err(e) => {
            tracing::error!("Failed to read routes config: {}", e);
            StaticRoutesConfig::default()
        }
    }
}

/// Save static routes to disk.
pub fn save_static_routes(config: &StaticRoutesConfig) -> Result<(), Box<dyn std::error::Error>> {
    let yaml = serde_yaml::to_string(config)?;
    std::fs::write(ROUTES_CONFIG_PATH, &yaml)?;
    Ok(())
}

/// Generate FRR static routes section.
pub fn generate_static_frr(config: &StaticRoutesConfig) -> String {
    let mut frr = String::new();

    for route in &config.routes {
        frr.push_str(&format!(
            "ip route {} {} {}\n",
            route.cidr, route.gateway, route.metric
        ));
    }

    if !config.routes.is_empty() {
        frr.push_str("!\n");
    }

    frr
}

/// Generate complete FRR configuration.
pub fn generate_frr_config(
    ospf: &ospf::OspfConfig,
    bgp: &bgp::BgpConfig,
    static_routes: &StaticRoutesConfig,
) -> String {
    let mut frr = String::new();

    frr.push_str("! Generated by QuickFW - do not edit manually\n");
    frr.push_str("frr version 8.5\n");
    frr.push_str("frr defaults traditional\n");
    frr.push_str("hostname quickfw\n");
    frr.push_str("log syslog informational\n");
    frr.push_str("service integrated-vtysh-config\n");
    frr.push_str("!\n");

    // Static routes
    frr.push_str(&generate_static_frr(static_routes));

    // OSPF
    frr.push_str(&ospf::generate_ospf_frr(ospf));

    // BGP
    frr.push_str(&bgp::generate_bgp_frr(bgp));

    frr.push_str("line vty\n!\n");

    frr
}

/// Apply FRR configuration by writing to /etc/frr/frr.conf and reloading.
pub fn apply_frr_config(frr_conf: &str) -> Result<(), Box<dyn std::error::Error>> {
    // Write config
    std::fs::write("/etc/frr/frr.conf", frr_conf)?;

    // Set permissions
    let _ = std::process::Command::new("chown")
        .args(["frr:frr", "/etc/frr/frr.conf"])
        .output();
    let _ = std::process::Command::new("chmod")
        .args(["640", "/etc/frr/frr.conf"])
        .output();

    // Reload FRR
    let output = std::process::Command::new("systemctl")
        .args(["reload", "frr"])
        .output()?;

    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        tracing::error!("Failed to reload FRR: {}", stderr);
        return Err(format!("FRR reload failed: {}", stderr).into());
    }

    tracing::info!("FRR configuration applied successfully");
    Ok(())
}

/// Execute a vtysh command and return output.
pub fn vtysh_command(args: &[&str]) -> Result<String, Box<dyn std::error::Error>> {
    let mut cmd = std::process::Command::new("vtysh");
    cmd.args(args);
    let output = cmd.output()?;

    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        return Err(format!("vtysh failed: {}", stderr).into());
    }

    Ok(String::from_utf8_lossy(&output.stdout).to_string())
}

/// Get OSPF neighbors from vtysh.
pub fn get_ospf_neighbors() -> Result<String, Box<dyn std::error::Error>> {
    vtysh_command(&["-c", "show ip ospf neighbor"])
}

/// Get BGP summary from vtysh.
pub fn get_bgp_summary() -> Result<String, Box<dyn std::error::Error>> {
    vtysh_command(&["-c", "show ip bgp summary"])
}

/// Get routing table from vtysh.
pub fn get_routing_table(protocol: Option<&str>) -> Result<String, Box<dyn std::error::Error>> {
    match protocol {
        Some("ospf") => vtysh_command(&["-c", "show ip route ospf"]),
        Some("bgp") => vtysh_command(&["-c", "show ip route bgp"]),
        Some("connected") => vtysh_command(&["-c", "show ip route connected"]),
        Some("static") => vtysh_command(&["-c", "show ip route static"]),
        _ => vtysh_command(&["-c", "show ip route"]),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_generate_frr_config() {
        let ospf = ospf::OspfConfig {
            enabled: true,
            router_id: "1.1.1.1".to_string(),
            networks: vec![
                ospf::OspfNetwork { prefix: "192.168.1.0/24".to_string(), area: 0 },
            ],
            ..Default::default()
        };

        let bgp = bgp::BgpConfig {
            enabled: true,
            local_as: 65001,
            router_id: "1.1.1.1".to_string(),
            neighbors: vec![
                bgp::BgpNeighbor {
                    address: "10.0.0.1".to_string(),
                    remote_as: 65002,
                    ..Default::default()
                },
            ],
            ..Default::default()
        };

        let static_routes = StaticRoutesConfig {
            routes: vec![
                StaticRoute {
                    cidr: "0.0.0.0/0".to_string(),
                    gateway: "10.0.0.1".to_string(),
                    metric: 100,
                },
            ],
        };

        let frr = generate_frr_config(&ospf, &bgp, &static_routes);
        assert!(frr.contains("Generated by QuickFW"));
        assert!(frr.contains("router ospf"));
        assert!(frr.contains("router bgp 65001"));
        assert!(frr.contains("ip route 0.0.0.0/0 10.0.0.1 100"));
    }
}
