install cramfs /bin/false
install freevxfs /bin/false
install hfs /bin/false
install hfsplus /bin/false
install udf /bin/false
install dccp /bin/false
install sctp /bin/false
install rds /bin/false
install tipc /bin/false
install usb-storage /bin/false
install bluetooth /bin/false
install btusb /bin/false
install cfg80211 /bin/false
install mac80211 /bin/false
install firewire-core /bin/false
